// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3J3Rs39qvP-R2BTSYyZjBOMa9dWvdhnY',
    appId: '1:786796109481:web:46244da4286c3a411813b8',
    messagingSenderId: '786796109481',
    projectId: 'igeo-flutter',
    authDomain: 'igeo-flutter.firebaseapp.com',
    databaseURL: 'https://igeo-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'igeo-flutter.appspot.com',
    measurementId: 'G-36EW5F6FN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKYYWUENiO10mtLROqyHEls7sTyQJ0-Ts',
    appId: '1:786796109481:android:125212ca680d3cf41813b8',
    messagingSenderId: '786796109481',
    projectId: 'igeo-flutter',
    databaseURL: 'https://igeo-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'igeo-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtqoGw2nAo2THimeq2jRU2-qaV_EtEn8w',
    appId: '1:786796109481:ios:b634ed820c04a1fb1813b8',
    messagingSenderId: '786796109481',
    projectId: 'igeo-flutter',
    databaseURL: 'https://igeo-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'igeo-flutter.appspot.com',
    iosClientId: '786796109481-vn4s5fvrc653m69062lormivot22hvqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.igeoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtqoGw2nAo2THimeq2jRU2-qaV_EtEn8w',
    appId: '1:786796109481:ios:b634ed820c04a1fb1813b8',
    messagingSenderId: '786796109481',
    projectId: 'igeo-flutter',
    databaseURL: 'https://igeo-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'igeo-flutter.appspot.com',
    iosClientId: '786796109481-vn4s5fvrc653m69062lormivot22hvqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.igeoFlutter',
  );
}
