// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpU2GkH69Z-LgA0-dXBsyK8mt_e8Yg99c',
    appId: '1:234706913921:web:ffbbc0cf26bcd01fe65b80',
    messagingSenderId: '234706913921',
    projectId: 'igeo-e6789',
    authDomain: 'igeo-e6789.firebaseapp.com',
    storageBucket: 'igeo-e6789.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdyaODdBjO4rePiVD3x8wICSRTpBwNE5E',
    appId: '1:234706913921:android:900f382a3b9b4898e65b80',
    messagingSenderId: '234706913921',
    projectId: 'igeo-e6789',
    storageBucket: 'igeo-e6789.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzhp0u1wHxaEJ_ff1v2baTsT-vQF_CGi8',
    appId: '1:234706913921:ios:b806d8048c9db45fe65b80',
    messagingSenderId: '234706913921',
    projectId: 'igeo-e6789',
    storageBucket: 'igeo-e6789.appspot.com',
    iosClientId: '234706913921-4k83cb660t3sm8t00mmkbo4q9tlc04rc.apps.googleusercontent.com',
    iosBundleId: 'com.example.igeoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzhp0u1wHxaEJ_ff1v2baTsT-vQF_CGi8',
    appId: '1:234706913921:ios:b806d8048c9db45fe65b80',
    messagingSenderId: '234706913921',
    projectId: 'igeo-e6789',
    storageBucket: 'igeo-e6789.appspot.com',
    iosClientId: '234706913921-4k83cb660t3sm8t00mmkbo4q9tlc04rc.apps.googleusercontent.com',
    iosBundleId: 'com.example.igeoFlutter',
  );
}
